version: "3.4"
services:
  db:
    image: mdillon/postgis
    volumes: 
      - data-volume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 123456
    networks:
      backend:
        ipv4_address: 172.16.238.10
  app:
    build: ./charts_analyzier
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes: 
      - ./charts_analyzier/data/:/Wartsila/charts_analyzier/data/
    networks:
      backend:
        ipv4_address: 172.16.238.11
volumes: 
  data-volume:
networks:
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.16.238.0/24"
 